### ISSUE TITLE
Conflicting versions of various pip packages

### ISSUE THREAD

**Issue by PranjalRoy123** [SaptakBhoumik/WebPlus#4]
Hi. I am facing an issue that one of my package version is conflicting while downloading another package
How to fix:
Add version in every package name in requirements.txt. For ex pygame==2.0.0, etc.
Thank you in advance

**Comment by SaptakBhoumik** [comment]
I have updated the requirements.txt so please check it out.  "**Hi. I am facing an issue that one of my package version is conflicting while downloading another package**" Can you please send me the screenshot of the issue that you are facing since I didn't understand what do you want to tell. If you like web plus please star the repository, contribute to the code and share it as it is very helpful

**Comment by SaptakBhoumik** [comment]
@PranjalRoy123  I have updated the requirements.txt so please check it out.  "**Hi. I am facing an issue that one of my package version is conflicting while downloading another package**" Can you please send me the screenshot of the issue that you are facing since I didn't understand what do you want to tell. If you like web plus please star the repository, contribute to the code and share it as it is very helpful

**Comment by SaptakBhoumik** [comment]
@PranjalRoy123 If you face any other problem feel free to contact me
